name: CI Pipeline | by aCloverophile

on:
  push:
    branches:
      - feature/lab3
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 23
      uses: actions/setup-java@v2
      with:
        java-version: "23"
        distribution: "temurin"

    - name: Add Execute Permissions for Gradle Wrapper
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Run Unit Tests
      run: ./gradlew test jacocoTestReport

    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      with:
        args: >
          -Dsonar.projectKey=lab-3-aCloverophile
          -Dsonar.organization=bhos-qa
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
